name: AuthPlugin
version: 1.0
main: com.rickrocha.AuthPlugin
author: Rick Rocha
description: My First AuthPlugin

commands:
  auth:
    description: A command to authenticate users.
    usage: /<command>
