name: AuthPlugin
version: 1.0
main: com.rickrocha.AuthPlugin
author: Rick Rocha
description: My First AuthPlugin

commands:
  register:
    description: Register a new user.
    usage: /register <password> <confirm password>
  login:
    description: Login a user.
    usage: /login <password>
